---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq
  namespace: sa-p8
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgB5DVZhH64V5ywv0G3jPGCjOKjdZoLl8TwEAAYY11U+uegCu0VDy8I994DKej7k1SPjr3P519z7awJS5PyIJbkkHX6kP9d1eOjIvxqsFJ04IG8PIF4fvff3y8xP4wqphqcD9iYM/jdKjAJCQWYejff+Q9V2ewaVEtjnhdEGnTNHYhnrSliRbzyYaJDJHjfypTc8YVJA2GHzMNUYOr4N7ZytD58gAx8iV9lCHvK0qYHeWQykJt0nB0ZRGTYFf845lJVDFSvdzrOmoDhp1ZII6u7jhYATZB9f3jBwc3JrAczJetXAA/rMdYyN3DhqOlsQcyty/aKtj/BGyHsFmk8CoM2rSeU8iyjK92txz6mVZ5zG4q9CwMBHgnzRDfCa2LcqRbQkJvxiONCyyK/DlNH9NvSzc1kxQQf8Ukd8ytFrlbymFQNF3b4Qgh4ViO5Yg2qBqkYFudeeHwpUmV0dgmaMOi7IKeDR4X9j1KdbC6lFMS876LZGZ4d4TS1WigKk3ZQVkxkW3qs0qG3ev5jp8QvINCYboGCjxehN8V9uTgaiMG410uhUVKTg3rWBSRbeTzh2O1x9Ccxzc/iYmModCUhNWlp9ykNhYmpPjgtbg0X9AEhxEq/qB5abct7FKJb7iFut5olVB8PFVnSldN72u4r3qH9nSdmDaXb8JmlLXPpg/ox679W2kDdr4RI7tUsj36AbBcBLAlWMftdAZt0Tr2NIdnSQdO3eUQ6NyAhpQxb18W1emlCd+wQg7fLJ
    rabbitmq-password: AgAfTzeiUikQKEbYmhtieeVxC0Ma3J7GQVbD6ECXBu3+iFjU3gHGAh4+lBlupMcUuaPblUgNQncWnNWd0RixQRhbgd0W6zJDtdl0U/dXlHQntgDYYGgRE2Ke2Yc82zGxvti7Aw3GTMYPDAjSCwrzUKGJXvVqqT7GS+VmRkKOvlAchP0HyXrqN5Ywo7XCkCZvcUM/NgO5qwgDaYTDhiU7U5L96hNHrwUEGQr6CTuMEUKNP104UCEUhPdaxsHjDmCasAj77+iM2aFXQLQF6E5SsQkeA/uQAjtT5WpeW2CuIhacdgx1QRLYrHabiMcIz9sEHFoQK5aINn9LJYu7q3hStMRAPc5WmLFYquCiK8WccGchAbnkngccL3VJRU3tXODoyL22Banwc4sDDTNENwsMx/ZombCaHsZdl16aS8go7UEeytFwl/Ne7OOdzrwl1pGh+NLAO8GARZEfUkdfCGLAfItSBVdYQSLucC4KcqG6itTeSqfAgXtS3vTtEmIkCl7RRnSEAzJVbZzOoJQ3OH1Zx3LmH3tb6g5kM1IrJC6ube/Kq7Bap5qw1nKBFu/xeVIFvJKXQnLFIKrr6PhQsuPNtOTaBmBXTl73eLTRPT3cqN3Z+ksn6SZoTW/xH28O/WAWPuCoBzOXThoEdyOBdj6VLma7xXNY4FYuE5gkgncUUpKz3iC11P4HNjU96wURlao0keB3fQakJ8eG3EnZnue+JaupKWJvzHFTTSkEABrs/KMicg==
  template:
    metadata:
      name: rabbitmq
      namespace: sa-p8
