---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-p5-shared-secrets
  namespace: sa-p8
spec:
  encryptedData:
    JWT_SECRET: AgBDZGEikWrN77wQSnSFUkOjfDBTva6cTuPX3eOlSKhWdfp1wS/USemCzkpYwcwvphizMQxCNm53vKNmFbr7T7rTQ78gCD1XeUEMLrPwPc+d/a+y6Kd6k61MEvS6U9rqa/0NTWY8sgaVaL6OE15a023BjY42+GN3bq8OLQ1L7+TpW+vJlKXI2SijwsRt2hBD0BQfX8x6uvTeJyHFRfN70dc+7oBipo6AOWu2IqVCb093EkHceXyPw+5f28h7+9zUvIouY2KRmmltsrYOvwkpSIRMtGyC63uPJL7jGj902zzZ31N5fBWb3m/SCmBj7wwG5BvSZXxj4zWUKBytze9g8IsTU4ku+h/kYnkQgWpjvL0ir+prsRKc+4MsVFqDUuOkROlidVkxmB+I8Ln3onNwAa21LWXzAMbOwktXdnZm9/bMfcHa8FMx9maOpivm7WIg1uN3K5zYaYX9tK19l2uQTTuhnlIZBovfQmCuDd3ITnT44JYnLhH8vnwudIMkkaGa2r13N/9ZZ+wp832FfwzaRspyZeFaYfraiG2UyCf5tOSYU7xQuVnx2h2RDKjUJmQmQyC+fJZVld5cVE6+7w9gxfoTTf2by8RK3iUrC6IAOeLNe5V1EUqaEncdTK/W84sICC4Y1b+KpveLKwcm1cts9YRlxMdzZs3AauSNl1dq/SrlbZiyN3hoBSMltPhwNQyCOO74Qd6Red9S2FiPZN4FXgFex1RJvUFhAKC5qOMy0CFZyyaOtbiT4w4rfIkNvIb4hx/hKKzDOIcaZjqYyI+K5Ctk
  template:
    metadata:
      name: sa-p5-shared-secrets
      namespace: sa-p8
