apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-config
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.port | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | default "info" | quote }}
  AUTH_SERVICE_URL: {{ required "api-gateway: falta config.authServiceUrl" .Values.config.authServiceUrl | quote }}
  PRODUCTOS_SERVICE_URL: {{ required "api-gateway: falta config.productosServiceUrl" .Values.config.productosServiceUrl | quote }}
  REPORTES_SERVICE_URL: {{ required "api-gateway: falta config.reportesServiceUrl" .Values.config.reportesServiceUrl | quote }}
  PEDIDOS_SERVICE_URL: {{ required "api-gateway: falta config.pedidosServiceUrl" .Values.config.pedidosServiceUrl | quote }}
